#include "pitches.h"

#define PLAY 0
#define REC 1
#define SING 2

#define JUST_PRESSED 1
#define JUST_RELEASED 2

// DEFINITIONS

#define NOT_TOGGLED 0
#define PRESSED 1
#define RELEASED 2

#define KEYBOARD_LENGTH 8
#define PLAYING_NOTES_CAP 100

#define RECORD_CAP 100
#define PAUSE_BETWEEN_SONGS 500 // milliseconds

// utilities
#define RECORD_BUTTON 37
#define CHANGE_OCTAVE_BUTTON 35

// piezo
#define PIEZO_OUTPUT_1 2
#define PIEZO_OUTPUT_2 3

// PIANO BUTTONS
#define FIRST 53
#define SECOND 51
#define THIRD 49
#define FOURTH 47
#define FIFTH 45
#define SIXTH 43
#define SEVENTH 41
#define EIGHTH 39

int octaves[7][8] = {
    {NOTE_C1, NOTE_D1, NOTE_E1, NOTE_F1, NOTE_G1, NOTE_A1, NOTE_B1, NOTE_C2},
    {NOTE_C2, NOTE_D2, NOTE_E2, NOTE_F2, NOTE_G2, NOTE_A2, NOTE_B2, NOTE_C3},
    {NOTE_C3, NOTE_D3, NOTE_E3, NOTE_F3, NOTE_G3, NOTE_A3, NOTE_B3, NOTE_C4},
    {NOTE_C4, NOTE_D4, NOTE_E4, NOTE_F4, NOTE_G4, NOTE_A4, NOTE_B4, NOTE_C5},
    {NOTE_C5, NOTE_D5, NOTE_E5, NOTE_F5, NOTE_G5, NOTE_A5, NOTE_B5, NOTE_C6},
    {NOTE_C6, NOTE_D6, NOTE_E6, NOTE_F6, NOTE_G6, NOTE_A6, NOTE_B6, NOTE_C7},
    {NOTE_C7, NOTE_D7, NOTE_E7, NOTE_F7, NOTE_G7, NOTE_A7, NOTE_B7, NOTE_C8}};